dbdriver: mysql
datasource: testuser:Rewghikpatgiwy@/mysql_vs_pgsql
stages:
- stage: initialStageSubstage1
  rps: 100
  concurrency: 20
  duration: 600s
  runonce: []
  repeat:
  - scenario: populateTheDB
    queries:
    - query: simpleInsertUser
      sql: INSERT INTO users(user_name) VALUES(?)
      params:
        - param: UserName
          type: string
          generator: RandUUID
      update: true
    - query: simpleInsertUserMessage
      sql: INSERT INTO messages(user_id, ctime, message) VALUES(?,?,?)
      params:
        - param: UserId
          type: int
          generator: RandToFirstQueryCallCounter
        - param: CTime
          type: timestamp
          generator: Now
        - param: Message
          type: string
          generator: Rand4KText
      update: true
      randrepeat: 10
    probability: 1
  pause: false
