stages:
- stage: initialStageSubstage1
  rps: 100
  concurrency: 10
  duration: 20s
  runonce:
  - query: simpleSelect
    sql: SELECT 1 FROM DUAL
    update: false
    probability: 1
  - query: simpleSelect2
    sql: SELECT 1 FROM DUAL
    update: false
    probability: 1
  repeat: []
  pause: false
- stage: initialStageSubstage2
  rps: 300
  concurrency: 10
  duration: 1m0s
  runonce:
  - query: simpleSelect
    sql: SELECT 1 FROM DUAL
    update: false
    probability: 1
  repeat:
  - query: simpleSelect
    sql: SELECT 1 FROM DUAL
    update: false
    probability: 1
  - query: simpleInsert
    sql: INSERT INTO table1('name', 'value') VALUES({{ .Rand1 }}, {{ .Rand2 }})
    update: true
    probability: 0.9
  pause: false
