- hosts: all
  become: yes
  roles:
  - role: etckeeper
  - role: common-utils

- hosts: postgresql-master
  become: yes
  roles:
  - role: postgresql

- hosts: postgresql-slave
  become: yes
  roles:
  - role: postgresql
